# Generated by Django 5.2.7 on 2025-10-11 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produk',
            name='kategori',
        ),
        migrations.AddField(
            model_name='produk',
            name='kategori',
            field=models.ManyToManyField(related_name='produk', to='toko.kategori'),
        ),
    ]
