# Generated by Django 5.2.7 on 2025-11-04 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0002_remove_produk_kategori_produk_kategori'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_depan', models.CharField(max_length=100)),
                ('nama_belakang', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telepon', models.CharField(max_length=20)),
                ('alamat', models.CharField(max_length=255)),
                ('kota', models.CharField(max_length=100)),
                ('kode_pos', models.CharField(max_length=10)),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
                ('total_bayar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lunas', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-dibuat',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harga', models.DecimalField(decimal_places=2, max_digits=10)),
                ('jumlah', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='toko.order')),
                ('produk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='toko.produk')),
            ],
        ),
    ]
