# Generated by Django 5.2.7 on 2025-11-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0004_order_bukti_pembayaran'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subjek', models.CharField(max_length=200)),
                ('pesan', models.TextField()),
                ('dibuat', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-dibuat',),
            },
        ),
    ]
