# Generated by Django 5.2.7 on 2025-11-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0006_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='nomor_resi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status_pengiriman',
            field=models.CharField(choices=[('pending', 'Menunggu Diproses'), ('dikirim', 'Telah Dikirim'), ('selesai', 'Selesai'), ('dibatalkan', 'Dibatalkan')], default='pending', max_length=20),
        ),
    ]
