# Generated by Django 5.2.7 on 2025-12-10 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0007_order_nomor_resi_order_status_pengiriman'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('confidence', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('lift', models.DecimalField(decimal_places=4, default=0, max_digits=6)),
                ('antecedent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='antecedent_rules', to='toko.produk')),
                ('consequent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consequent_rules', to='toko.produk')),
            ],
        ),
    ]
