# Generated by Django 5.2.7 on 2025-12-12 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toko', '0008_recommendationrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ongkir',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
